Write program in OOP. Add README.md
rubizza-survival-camp/summer-2018 pull request #261
Opened 2018-07-18 09:42 UTC by DenisVolchek

## Номер
2294

## Номер задания
2

## Ссылка на видео с демо
https://youtu.be/tfh_3mSzRe8

## Комментарии
Переписал "простыню"

2018-07-18 09:44 UTC, DenisVolchek commented
This errors are critical? can i desable reek?

2018-07-18 11:27 UTC, anatoliliotych requested changes

2018-07-21 06:49 UTC, anatoliliotych commented
why it doesn't match the task requirements?

2018-07-22 18:53 UTC, anatoliliotych requested changes

2018-07-22 18:53 UTC, anatoliliotych commented on 2294/2/analyze.rb
> +    [column_one, column_two, column_three, column_four, column_five]
strange naming...

2018-07-22 18:53 UTC, anatoliliotych commented on 2294/2/analyze.rb
> +# :reek:UtilityFunction
remove this.

2018-07-22 18:53 UTC, anatoliliotych commented on 2294/2/analyze.rb
> +    RussianObscenity.find(text).each do |bad|
try inject

2018-07-22 18:53 UTC, anatoliliotych commented on 2294/2/analyze.rb
> +    "#{bad_count} #{pluralize(bad_count, WORD_SETTING['two'])} #{pluralize(bad_count, WORD_SETTING['one'])}"
these one/two/three - are unreadable

2018-07-22 18:53 UTC, anatoliliotych commented on 2294/2/top_battlers.rb
> +    end.reverse
reverse! is faster.

2018-07-22 18:53 UTC, anatoliliotych commented on 2294/2/top_battlers.rb
> +    end.reverse
https://stackoverflow.com/questions/2642182/sorting-an-array-in-descending-order-in-ruby

2018-07-22 19:31 UTC, DenisVolchek commented on 2294/2/top_battlers.rb
> +# :reek:UtilityFunction
it's was written in gem documenation

2018-07-23 06:30 UTC, anatoliliotych requested changes

2018-07-23 06:30 UTC, anatoliliotych commented on 2294/2/top_words.rb
> +    rapers_exampels = @hash.keys.sample
typo, please avoid typos in variable/method names - use spellcheckers

2018-07-23 06:30 UTC, anatoliliotych commented on 2294/2/top_words.rb
> +    @hash[name].join(' ').split(' ').delete_if do |word|
what is the sense to join and then split back?

2018-07-23 06:30 UTC, anatoliliotych commented on 2294/2/app.rb
> +
why do you need this file? I thought that we agreed that it could be removed.

2018-07-23 06:30 UTC, anatoliliotych commented on 2294/2/file_parser.rb
> +    File.open("./rap-battles/#{file}") do |file_name|
you can put your folder name to constant

2018-07-23 17:33 UTC, anatoliliotych requested changes

2018-07-23 17:33 UTC, anatoliliotych commented on 2294/2/analyze.rb
> +  def bad_count
you should read about memoization: http://gavinmiller.io/2013/basics-of-ruby-memoization/

2018-07-23 17:33 UTC, anatoliliotych commented on 2294/2/file_parser.rb
> +    @rapers
this return is really unexpected

2018-07-23 17:33 UTC, anatoliliotych commented on 2294/2/top_battlers.rb
> +      @text = value.join(' ')
avoid using instance variables for such cases, were you need just pass reek.

2018-07-23 17:33 UTC, anatoliliotych commented on 2294/2/file_parser.rb
> +  def read_files
leave only this method as public

2026-07-14 07:45 UTC, closed without merging