2211-3
rubizza-survival-camp/summer-2018 pull request #296
Opened 2018-07-29 21:00 UTC by TanyaAkulich

## Номер
2211

## Номер задания
3

## Ссылка на видео с демо
https://youtu.be/14HoSWPaI7Y

## Комментарии

2018-07-30 14:22 UTC, nplusp requested changes
есть еще над чем поработать.
пиши вопросы если есть

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/Avr.rb
> +class Avr
что такое `Avr`?

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/Avr.rb
> +    @article_acore = 0
почему `acore`

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/LinkFilling.rb
> +class LinkFIlling
В имени класса `i` после `F` почему-то прописная.

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/LinkFilling.rb
> +  # rubocop: disable Style/RedundantParentheses
Не думаю, что это хорошая идея.
Есть какие-нибудь преимущества использования `(JSON(@response))` над `JSON(@response)`?

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/LinkFilling.rb
> +    (JSON(@response))['documents'].each do |elem|
Старайся называть переменные в блоках понятно.
Не `elem`, а `score`. 

А еще не `each`, а `each_with_object`.

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/LinkFilling.rb
> +    (JSON(@response))['documents'].each do |elem|
Конечно, лучше было бы закешировать работу с парсингом `response` в `JSON`, а то он у тебя в нескольких местах используется. Может, прям в initialize вынесешь, типа
```ruby
@documents = JSON.parse(response.body)['documents']
```

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/LinkFilling.rb
> +    @all_comments_texts.each_with_index do |com, index|
Здесь не `com`, а `comment`.

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/Parser.rb
> +    URI.parse('https://comments.api.onliner.by/news/tech.post/' + page_id + '/comments?limit=50')
урлы лучше в константу вынести и зафризить

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/Parser.rb
> +    json_comments['comments'].each_with_object([]) { |comment, array| array << comment['text'] }
а может можно просто сделать
```ruby
json_comments['comments'].map { |comment| comment['text'] }
```

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/Parser.rb
> +  def make_comments_list
мы обычно не добавляем предикаты `make_, set_, get_` и т.д. для методов.

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/PostQuere.rb
> +    @access_key = '8af30e06989641a7bab5f00d678b9c4d'
Вроде ж просили такое выносить в secrets.yml
Так делать нельзя, китайские краулеры не спят :)

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/PostQuere.rb
> +    @uri = URI('https://westcentralus.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment')
Вынеси в константу эту строку, плиз

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/PostQuere.rb
> +  # rubocop: disable Lint/UselessSetterCall
Не стоило выключать этот линтер.
Он ругается потому, что ты не возвращаешь инициированный объект в конце метода.
Поправь плз.

2018-07-30 14:22 UTC, nplusp commented on 2211/3/helpers/PostQuere.rb
> +    make_request
не совсем понимаю как это будет работать

2018-07-30 14:22 UTC, nplusp commented on 2211/3/views/add.erb
> +     <input type="text" name="link">
соблюдай вложенность, инпуты должны быть ниже уровнем чем форм

2018-07-30 14:22 UTC, nplusp commented on 2211/3/views/analysis.erb
> +    <%end%>
соблюдай отступы. еще мы обычно отделяем эти теги пробелами, типа `<% end %>`

2018-07-30 14:22 UTC, nplusp commented on 2211/3/views/index.erb
> +      <ul class='unstyled'>
это невалидный тег, внутри `ul` должны быть только `li`
а вот внутри `li` можешь вставить `a` :)

2018-07-30 14:22 UTC, nplusp commented on 2211/3/views/show.erb
> +    <p><a href=<%= "/add" %>>add new links</a></p>
здесь можно сделать просто `href='/add'` :)

2019-04-22 19:54 UTC, closed without merging

2019-04-22 20:30 UTC, stahor commented
Внезапно